### ISSUE TITLE
blendshape数据会公布么

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [tencent-ailab/hifi3dface#1]
大佬，blendshape的数据有公布的计划么

**Comment by cyj907** [comment]
> 大佬，blendshape的数据有公布的计划么

Expression blendshape吗？这篇文章只包含neutral face，表情是我们后续的工作哈，请继续关注哦~

**Comment by ZHANG-SHI-CHANG** [comment]
> > 大佬，blendshape的数据有公布的计划么
> 
> Expression blendshape吗？这篇文章只包含neutral face，表情是我们后续的工作哈，请继续关注哦~

赞

**Comment by johndpope** [comment]
I don’t speak Chinese but this might help https://github.com/jpl917/BlendshapeGeneration

**Comment by ZHANG-SHI-CHANG** [comment]
> I don’t speak Chinese but this might help https://github.com/jpl917/BlendshapeGeneration

yes，but expression database is not open yet
