### ISSUE TITLE
question about the depth data.

### ISSUE THREAD

**Issue by txjlx** [tencent-ailab/hifi3dface#11]
Thank you for your excellent work.

I have a question about the depth data.

Since I don't have an ios compile environment, I have to capture depth data with other equipment such as kinect.

I can't find the clear physical meaning of the uint of the iphone truedepth data on their website. 

Is it in millimeters after the calculation （dr*255 + dg）/ 10？

The data of kinect depth output stream is in millimeters, Can I take this data instead of the truedepth data of iphone.

Thank you.

**Comment by lxk121lalala** [comment]
The base unit of our input depth map is millimeters

**Comment by txjlx** [comment]
OK，Thanks for your response and kind reminder.
