### ISSUE TITLE
非刚性对齐的使用demo

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [tencent-ailab/hifi3dface#12]
非常赞的工作！
我注意到您这边用python实现了一个版本的非刚性对齐，请问能提供该工具的使用demo和一些运行效果么

**Comment by lxk121lalala** [comment]
可以参考我们论文中进行对比的非刚性对齐的效果。

**Comment by ZHANG-SHI-CHANG** [comment]
> 可以参考我们论文中进行对比的非刚性对齐的效果。

效果很好的，主要是调用的demo可以开源吗

**Comment by lxk121lalala** [comment]
调用的代码暂时不打算提供。
你可以参考原作者的代码repo，他提供了matlab的调用示例

**Comment by ZHANG-SHI-CHANG** [comment]
> 暂时

🙆，感谢回复
