### ISSUE TITLE
face shape拟合的过程中，使用的训练数据中只有采集的200人吗？

### ISSUE THREAD

**Issue by miaoYuanyuan** [tencent-ailab/hifi3dface#13]
你好，请问脸部shape参数拟合的过程中，使用的训练数据，只有采集的200人的4个角度照片吗？

**Comment by cyj907** [comment]
> 你好，请问脸部shape参数拟合的过程中，使用的训练数据，只有采集的200人的4个角度照片吗？

你说的是RGBD的优化过程吗？是优化，不涉及网络训练，数据是待重建个体的4张RGB-D照片

**Comment by miaoYuanyuan** [comment]
> 
> 
> > 你好，请问脸部shape参数拟合的过程中，使用的训练数据，只有采集的200人的4个角度照片吗？
> 
> 你说的是RGBD的优化过程吗？是优化，不涉及网络训练，数据是待重建个体的4张RGB-D照片

是的，明白了，多谢！
