### ISSUE TITLE
Could not generate rasterize_triangles_kernel.so

### ISSUE THREAD

**Issue by AIdeveloper-oz** [tencent-ailab/hifi3dface#14]
Hi, Thanks for sharing this awesome work. Having utmost interest in the working of this paper, I tried to test it's execution in google colaboratory. The normal method of running the "install.sh" is not working for me and hence I followed the direct installation of tf-meshrenderer from its own source. Everything goes well until the "rasterize_triangles_impl_test" is getting executed in the runtest.sh,

**ERROR: /content/hifi3dface/tf_mesh_renderer/mesh_renderer/kernels/BUILD:7:1: error loading package '@com_google_googletest//': Unable to load package for '@rules_cc//cc:defs.bzl': The repository could not be resolved and referenced by '//mesh_renderer/kernels:rasterize_triangles_impl_test'**

**ERROR: Analysis of target '//mesh_renderer/kernels:rasterize_triangles_impl_test' failed; build aborted: error loading package '@com_google_googletest//': Unable to load package for '@rules_cc//cc:defs.bzl': The repository could not be resolved**

This is my problem. Please help me overcome this issue or suggest me a solution to generate **rasterize_triangles_kernel.so**

Thanks in Advance!

**Comment by AIdeveloper-oz** [comment]
I got rid of the compilation issue, Now the install.sh is running without any errors, but still the  **rasterize_triangles_kernel.so** is not getting generated in the kernels folder.

**Comment by AIdeveloper-oz** [comment]
Got rid of this issue.

**Comment by kingseeking** [comment]
> I got rid of the compilation issue, Now the install.sh is running without any errors, but still the **rasterize_triangles_kernel.so** is not getting generated in the kernels folder.

how to solver '@com_google_googletest//' problem?

**Comment by KOAZZ** [comment]
How to solver '@com_google_googletest//' problem?
+1
