### ISSUE TITLE
AddHead Female

### ISSUE THREAD

**Issue by kyungjin-lee** [tencent-ailab/hifi3dface#16]
Hello, I've been trying with custom data and seems like add head tool doesn't work for female.
Even though I set the flag is_add_head_male as false it still seems to only generate the male head.
Wondering how to get this option working.
Thank you so much!

**Comment by haoxianzGit** [comment]
Hello, can you provide the image of your results?

**Comment by alisherakb** [comment]
Hi @kyungjin-lee,
Can you please share how did you solve an issue with compiling tf_mesh_renderer here? Especially, I am interested in your working versions of Cuda, Cudnn, Tensorflow and Bazel.
Thank you in advance!
