### ISSUE TITLE
RGBD results are not same as the demo output.

### ISSUE THREAD

**Issue by AIdeveloper-oz** [tencent-ailab/hifi3dface#18]
I used the RGBD capture module in  iphone 11 and captured the depth images similar to the test data. But my output seems to be messed. Not clear about where I went wrong. Help me generate the correct result as mentioned in the paper.

Also when I built the RGBD capture module in iphone X, the camera window opens, but capturing is not happening. What would be the reason for that?

FYI, I use Meshlab for viewing the outputs. 
Thanks in Advance!

![error](https://user-images.githubusercontent.com/59594140/100416078-9a368980-30a3-11eb-98e9-53763b1be596.PNG)

**Comment by haoxianzGit** [comment]
hello, you can try again, 
we have fixed this bug

**Comment by AIdeveloper-oz** [comment]
Hi @haoxianzGit, Thanks! Its working now. Yet, I didn't find any solution for my second question regarding iphone X. Do you have any idea on why it's not working in X?

**Comment by lxk121lalala** [comment]
Have you tried using the collection program we provide?
The test data we provide is collected using iphonex.
Maybe you need to check if the depth sensor of iPhone X is working properly

**Comment by AIdeveloper-oz** [comment]
I used the same collection code. It worked fine for iphone 11. Will check for any issues in the sensor. Anyways, Thanks for the reply.

**Comment by alisherakb** [comment]
Hi @AIdeveloper-oz ,
Can you please share how did you solve an issue with compiling tf_mesh_renderer here? Especially, I am interested in your working versions of Cuda, Cudnn, Tensorflow and Bazel.
Thank you in advance!
