### ISSUE TITLE
Windows Support - Installation tensorflow path

### ISSUE THREAD

**Issue by julienguegan** [tencent-ailab/hifi3dface#2]
Hello !

Does it support on windows ? Will it work if I try to adapt the install.sh script ?

**Comment by julienguegan** [comment]
I just kind of launch the **install.sh** using cygwin64 (tool providing linux environment for windows) but I then get 
` tensorflow/core/framework/op.h : No such file or directory` It seems to be an error with tensorflow path as it is not recognized ... Does it must be the same in the bash script and in the .h file ?

**Comment by cyj907** [comment]
> I just kind of launch the **install.sh** using cygwin64 (tool providing linux environment for windows) but I then get
> ` tensorflow/core/framework/op.h : No such file or directory` It seems to be an error with tensorflow path as it is not recognized ... Does it must be the same in the bash script and in the .h file ?

Hello, we did not test the codes with windows. I am not sure if tf_mesh_renderer supports windows.

The way to find the tensorflow library path depends on how you installed it. Different ways to install tensorflow or different versions can lead to different paths. So, the path in install.sh might not suit your case. You need to modify it so that the compilation can succeed.

Let me know if you can compile it and further questions are welcome. :)

**Comment by julienguegan** [comment]
OK, thank you for your response. I installed tensorflow on a conda environment so I just pointed to this path ... If needed I will then try on a linux virtual machine

**Comment by julienguegan** [comment]
Do you know if it has to be a specific version of tensorflow ? Or a certain way to be installed ? Because I just look in my directory **C:\Users\Miniconda3\envs\keras_env\Lib\site-packages\tensorflow_core\core\framework** and there is no `op.h` file only python files ... Can you describe what I should find in my tensorflow directory for the installation to succeed ? it would be a big help

**Comment by cyj907** [comment]
> Do you know if it has to be a specific version of tensorflow ? Or a certain way to be installed ? Because I just look in my directory **C:\Users\Miniconda3\envs\keras_env\Lib\site-packages\tensorflow_core\core\framework** and there is no `op.h` file only python files ... Can you describe what I should find in my tensorflow directory for the installation to succeed ? it would be a big help

I think the installation method might not support conda, see [here](https://github.com/tencent-ailab/hifi3dface/issues/6).

**Comment by julienguegan** [comment]
my path issue is resolved by pointed the tensorflow installation not in the environment directory but directly in **C:\Users\Miniconda3\lib\site-packages\tensorflow_core\** (but I have now an other error **cannot find -ltensorflow_framework** even the file libtensorflow_framework.so.1 is in the directory)

**Comment by cyj907** [comment]
> my path issue is resolved by pointed the tensorflow installation not in the environment directory but directly in *_C:\Users\Miniconda3\lib\site-packages\tensorflow_core*_ (but I have now an other error **cannot find -ltensorflow_framework** even the file libtensorflow_framework.so.1 is in the directory)

This can be solved by creating a soft link named "libtensorflow_framework.so" and point it to "libtensorflow_framework.so.1"
`ln -s libtensorflow_framework.so.1 libtensorflow_framework.so`
