### ISSUE TITLE
【BUG】bfs find bug in SparseFusion.py

### ISSUE THREAD

**Issue by LiuLinyun** [tencent-ailab/hifi3dface#25]
In file "optimization/rgbd/RGBD_utils/SparseFusion.py" line 57 :

queue = [[x + 1, y], [x - 1, y], [x, y - 1], [x, y - 1]]

the last element [x, y-1] should be [x, y+1] ?

because it is a bfs algorithm and coordinate [x, y+1] will be visited in next loop immediately, maybe this bug will not have much bad effect on result.

**Comment by lxk121lalala** [comment]
Thank you. We'll fix it right away

**Comment by haoxianzGit** [comment]
We have fixed this bug.
Thank you.
