### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by clumsynope** [tencent-ailab/hifi3dface#3]
FileNotFoundError: [Errno 2] No such file or directory: './resources/diffuse/2k_F_EAS_face_026_D.tga'

**Comment by cyj907** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: './resources/diffuse/2k_F_EAS_face_026_D.tga'

Can you provide all of the error information? We want to know where the error happens.
Thank you.

**Comment by haoxianzGit** [comment]
We have fixed this bug. 
Thank you.

**Comment by clumsynope** [comment]
Thanks for your help.
