### ISSUE TITLE
About the input image size:

### ISSUE THREAD

**Issue by Barry-Liang** [tencent-ailab/hifi3dface#9]
Is it possible to input images with size 1920*1080 and not resize them to 640*480? In addition, the camera intrinsic will maintain the same from the 1920*1080 camera calibration. I am not sure whether there are some limitations to force users to use a certain size 640*480.  And if a large size is possible, do I need to change the crop size 300*300?

**Comment by cyj907** [comment]
> Is it possible to input images with size 1920_1080 and not resize them to 640_480? In addition, the camera intrinsic will maintain the same from the 1920_1080 camera calibration. I am not sure whether there are some limitations to force users to use a certain size 640_480. And if a large size is possible, do I need to change the crop size 300*300?

If you want to use other image resolution, you may have to modify the codes. We fix them for iphone RGBD capture, not because of algo limitation. The camera intrinsics should be changed for different devices.

Of course you can change other crop size than 300 * 300. We use this resolution because it is large enough to get a satisfactory result. But you may have to modify the codes a bit.

**Comment by Barry-Liang** [comment]
Thanks for your reply. I want to make the question more clear. Now the result for my personal data is not good, especially the geometry of the head. I think the geometry comes from the RGBD optimization part, right? Therefore, the head geometry is only related to the four selected RGBD frames.  I use the size 640x576. I think it is similar with the 640x480. which part of the code do you think I need to modify so that it can match a new size?

**Comment by Barry-Liang** [comment]
Do you mean the geometry optimization part requires a fixed size of image input so I need to reshape them into 640x480? I notice that there is a comment #  load img and depth , change to 640 * 480 in step0_prepare_frontend_data.py, but to resize codes there.  should I resize both the img and landmark to the 640x480 size in that py file?

**Comment by arpu** [comment]
anyone can provide  some RGB-d input images?  ( i have no iphone)

**Comment by arpu** [comment]
sorry found it in test_data.zip!

**Comment by haoxianzGit** [comment]
> Thanks for your reply. I want to make the question more clear. Now the result for my personal data is not good, especially the geometry of the head. I think the geometry comes from the RGBD optimization part, right? Therefore, the head geometry is only related to the four selected RGBD frames. I use the size 640x576. I think it is similar with the 640x480. which part of the code do you think I need to modify so that it can match a new size?

Hello, can you provide the image of your input and result?

**Comment by Barry-Liang** [comment]
Sorry, problem solved. It's my mistake.
